-- 15 espèces
insert into public.species (id, sci, common_name, classification, family, day_night, rarity, size, description, note, photo) values
  ('flabellina-exopata', 'Flabellina exopata', '', 'Éolide', 'Flabellinidae', '', 3, '2 à 4 cm', '["Cérates irisées bleu/blanc sur un corps brun-orange","Se nourrit d''hydroïdes","Présente sur les éponges et récifs de Bora Bora"]'::jsonb, 'Ses cérates contiennent les cellules urticantes de ses proies — elle se défend avec leur propre arsenal.', 'assets/species/flabellina-exopata.jpg'),
  ('chromodoris-sp3', 'Chromodoris sp3', '', 'Doridacé', 'Chromodorididae', '', 4, '~ 2 cm', '["Corps blanc-bleu pâle strié de lignes bleu marine","Rhinophores orange vif","Se nourrit d''éponges"]'::jsonb, 'Le « sp3 » signifie : espèce pas encore officiellement décrite. Il reste des découvertes à faire à Bora Bora.', 'assets/species/chromodoris-sp3.jpg'),
  ('diversidoris-flava', 'Diversidoris flava', '', 'Doridacé', 'Chromodorididae', '', 4, 'quelques mm', '["Corps jaune translucide — on voit ses organes internes","Quasi invisible à l''œil nu","L''adulte sera très différent : brun tacheté"]'::jsonb, 'Celui-ci fait à peine quelques millimètres. Le trouver, c''est déjà une victoire.', 'assets/species/diversidoris-flava.jpg'),
  ('chromodoris-sp1', 'Chromodoris sp1', '', 'Doridacé', 'Chromodorididae', '', 4, '~ 2 cm', '["Corps blanc nacré, taches brun-or, liseré bleu marine","Rosette branchiale bleu-violet","Se nourrit d''éponges"]'::jsonb, 'Comme le sp3 — espèce encore non décrite officiellement. Bora Bora a encore des secrets à livrer.', 'assets/species/chromodoris-sp1.jpg'),
  ('gymnodoris-ceylonica', 'Gymnodoris ceylonica', '', 'Doridacé', 'Gymnodorididae', '', 3, '3 à 5 cm', '["Corps blanc translucide, pois rouge vif, liseré orange","Prédateur — se nourrit d''autres nudibranches","En reproduction : agrégations de dizaines d''individus"]'::jsonb, 'Observés par dizaines un matin à Bora Bora avec Dive N'' Smile — un événement encore peu documenté en Polynésie.', 'assets/species/gymnodoris-ceylonica.jpg'),
  ('micromelo-undatus', 'Micromelo undatus', '', 'Bulle', 'Aplustridae', '', 3, '1 à 2 cm', '["Manteau translucide bleu-gris, taches blanches, liseré jaune vif","Réseau de lignes rouge bordeaux","Possède encore une coquille interne réduite"]'::jsonb, 'Pas tout à fait un nudibranche, pas tout à fait un escargot — la nature aime brouiller les pistes.', 'assets/species/micromelo-undatus.jpg'),
  ('phyllidia-carlsonhoffi', 'Phyllidia carlsonhoffi', '', 'Doridacé', 'Phyllidiidae', '', 2, '3 à 6 cm', '["Corps noir intense, tubercules jaune or cerclés de blanc","Pas de rosette : respire par le bord du manteau","Se nourrit d''éponges toxiques et stocke leurs toxines"]'::jsonb, 'Son motif noir/jaune est un avertissement : « je suis toxique, ne me mange pas. »', 'assets/species/phyllidia-carlsonhoffi.jpg'),
  ('goniobranchus-kuniei', 'Goniobranchus kuniei', '', 'Doridacé', 'Chromodorididae', '', 1, '6 à 8 cm', '["Corps jaune-crème, taches noires, liseré bleu-violet","Rosette branchiale bien développée","Indo-Pacifique, fréquente en Polynésie"]'::jsonb, 'Une des plus grandes du récif — même les plongeurs qui ne regardent pas le fond la remarquent !', 'assets/species/goniobranchus-kuniei.jpg'),
  ('phyllidiella-rosans', 'Phyllidiella cf. rosans', '', 'Doridacé', 'Phyllidiidae', '', 2, '2 à 4 cm', '["Corps rose-bleu pâle, larges bandes noires","Respire par le bord du manteau (pas de rosette visible)","Se nourrit d''éponges toxiques"]'::jsonb, 'Le « cf. » indique une identification non certaine à 100 %.', 'assets/species/phyllidiella-rosans.jpg'),
  ('phyllidiella-annulata', 'Phyllidiella annulata', '', 'Doridacé', 'Phyllidiidae', '', 2, '2 à 4 cm', '["Corps noir, gros tubercules rose-saumon","Rhinophores noirs — presque invisibles","Respire par le bord du manteau"]'::jsonb, 'Noir et rose, sobre et sophistiquée. La plus élégante du récif ?', 'assets/species/phyllidiella-annulata.jpg'),
  ('risbecia-imperialis', 'Risbecia imperialis', '', 'Doridacé', 'Chromodorididae', '', 2, '5 à 8 cm', '["Corps blanc-bleu, pois jaune vif, rhinophores rayés noir/blanc","Comportement de « following » : l''un suit l''autre en touchant sa queue","Se nourrit d''éponges"]'::jsonb, 'Le following : une danse lente et silencieuse, museau contre queue.', 'assets/species/risbecia-imperialis.jpg'),
  ('pseudoceros-scintillatus', 'Pseudoceros scintillatus', '', 'Ver plat', 'Pseudocerotidae', '', 3, 'quelques mm', '["Corps blanc, réseau de lignes et taches noires","Extrémités blanches à pointe orange","Se cache dans les algues et le biofilm"]'::jsonb, 'Techniquement un ver plat (plathelminthe), très souvent confondu avec un nudibranche.', 'assets/species/pseudoceros-scintillatus.jpg'),
  ('thuridilla-gracilis', 'Thuridilla gracilis', '', 'Sacoglosse', 'Plakobranchidae', '', 2, '2 à 3 cm', '["Pattern complexe brun/noir/jaune, points bleu électrique","Aspire le contenu des algues dont elle se nourrit","Stocke les chloroplastes des algues dans ses tissus"]'::jsonb, 'Elle vole les chloroplastes des algues et les fait fonctionner — mi-animal, mi-plante. Elle photosynthétise !', 'assets/species/thuridilla-gracilis.jpg'),
  ('dolabella-auricularia', 'Dolabella auricularia', '', 'Lièvre de mer', 'Aplysiidae', '', 3, 'jusqu''à 15 cm', '["Corps brun, parfaitement camouflé dans le sable","Normalement nocturne — le croiser de jour est un privilège","Herbivore : broute les algues et entretient les herbiers"]'::jsonb, 'Un discret jardinier du lagon polynésien.', 'assets/species/dolabella-auricularia.jpg'),
  ('miamira-miamirana', 'Miamira miamirana', '', 'Doridacé', 'Chromodorididae', '', 5, 'jusqu''à 15 cm', '["Corps crème bosselé, tons kaki et lilas, siphons dressés","Silhouette unique, presque végétale","Rencontre rare à Bora Bora — observée avec Dive N'' Smile"]'::jsonb, 'Même en la regardant droit dans les yeux, on se demande si c''est bien un animal.', 'assets/species/miamira-miamirana.jpg')
on conflict (id) do nothing;
